---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mywebdeploy
  labels:
    app: mywebdeploy
spec:
  selector:
    matchLabels:
      app: mywebdeploy
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mywebdeploy
        tier: frontend
    spec:
      containers:
      - image: httpd:latest
        name: httpd-container
        ports:
        - containerPort: 80
          name: httpd 
        volumeMounts:
        - name: httpd-volume
          mountPath: /usr/local/apache2/htdocs
      volumes:
      - name: httpd-volume
        persistentVolumeClaim:
          claimName: my-httpd-pvc
