apiVersion: v1
kind: Service
metadata:
  name: mywebdeploy
  namespace: default
  labels:
    app: mywebdeploy
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mywebdeploy
    tier: frontend
  type: LoadBalancer
